# Generated by Django 4.1.4 on 2022-12-26 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('link', models.CharField(max_length=150, verbose_name='Посилання')),
                ('file', models.FileField(null=True, upload_to='')),
                ('description', models.TextField(blank=True, verbose_name='Текст')),
                ('about_file', models.CharField(blank=True, max_length=200, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Doc',
                'ordering': ['about_file', 'name', 'updated_at', 'link'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LineOfDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=600, verbose_name='Текст рядка')),
            ],
        ),
        migrations.CreateModel(
            name='WordOfDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Слово')),
                ('lineOfDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_info.lineofdoc')),
            ],
        ),
    ]
