# Generated by Django 4.1.4 on 2022-12-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва принтера')),
                ('api_key', models.CharField(max_length=150, verbose_name='Ключ доступу до API')),
                ('check_type', models.BooleanField(blank=True, max_length=150, verbose_name='Чек для клієнта ?')),
                ('point_id', models.IntegerField(verbose_name='ID Принтера')),
            ],
            options={
                'verbose_name': 'Checks',
                'ordering': ['api_key', 'name', 'check_type', 'point_id'],
            },
        ),
    ]
